apiVersion: ENC[AES256_GCM,data:HElf57vv+y+X4WAvcN6c0PDlNMI=,iv:8bkKeQXvmPbgwWXtm4/mw8ahVrhP/eDpVY8eXPUS/jg=,tag:h/0ny/Wmn16ZErG51Njiow==,type:str]
kind: ENC[AES256_GCM,data:+VlG5nxnS7eCRw==,iv:4wis4GehIhvIXpUbdKiYHk3Lb6Ib/ZThVPk4G8aynpU=,tag:0MZxEg+C2yTX8kTf9wdgqA==,type:str]
metadata:
    labels:
        terragrunt: ENC[AES256_GCM,data:5Y95XQ==,iv:jquA1Ua4Epk9iPWBbQ/7hAHw3ev5Sm4JAjXskwxZtFM=,tag:0EG2XqY7TBm0rtZDRziN7w==,type:str]
        opentofu: ENC[AES256_GCM,data:OtZZhA==,iv:IgUMEjbvFqbkD021DAcldqRjeu1yuvhCeA/SujaeuiY=,tag:GOtpQj8N+l4V1RBB4KrjCA==,type:str]
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:Cpem,iv:28lIC2tig5kO+TUsNqFMoZXSnWRJzS3F0wHvsuqLIZ0=,tag:70B6t9XOTLRJkhKzPpomtQ==,type:str]
    name: ENC[AES256_GCM,data:U+SWJTWnqyP1T7ZiFD7gAYv90gF1YYshmJzcNA551ns=,iv:vFaXgz2aFICMj3V58EuDwDTu++NyKgMcFBIjKuw0r5Y=,tag:2Ed66WGCSU5YnmIL1SvWhA==,type:str]
    namespace: ENC[AES256_GCM,data:zweqswBx,iv:4miO9RKGwmavqG43fiFcnvLSMEkvD+B8pDv87FEA6sE=,tag:4o2S2ZJ9O4wejp4o2iTjQg==,type:str]
    finalizers:
        - ENC[AES256_GCM,data:NELurxa+rX3MnJwU84IVq1k7tc0WlfvLnUzO7VK3/vkqAXXEz4c=,iv:IvAc7/wS9oKGIt/elw3NzTlu3pskWepkPFSRa4DMFTw=,tag:RE8/FejurFW5nqqF3mPk7A==,type:str]
spec:
    description: ENC[AES256_GCM,data:uLcaxb0RAvUW3sTVCba2KAnlwhrOAkXd+g7i8wkX2dR83M+AOQVyQ30=,iv:YVV1VF+h7OQxLHzcjHbSH0iRYkoWRjZCsDOL0kmsLYc=,tag:7rKCcNCGA8Kd6CygUyYxnA==,type:str]
    sourceRepos:
        - ENC[AES256_GCM,data:ew==,iv:4SuQlRwfVd32G/IavyUGfSXKdcgfa3Fco7+nzylBs34=,tag:hLLcFydSIN4sx61270ZTVw==,type:str]
    destinations:
        - namespace: ENC[AES256_GCM,data:PQ==,iv:bBB6uxNxRn+2lG4/DmkzAauQAkNUxz6iTWFeK+DqnSQ=,tag:sK0exMm7OkXbzzq++cQxyw==,type:str]
          server: ENC[AES256_GCM,data:uGxMGb4RvJECPIm4o8UR8Qwh3YSfP5GnrDSXfPrh0NW4WApnymRpevl5Wc0=,iv:rx6CPfrpBYBh/QepYqNVzt0y4tJlXj6bauZK1PnUs6o=,tag:9IojY+r1qjpTUonzfmAJOQ==,type:str]
          name: ENC[AES256_GCM,data:xB1oJ0R4Q9+DdA==,iv:KQn55dAdE6Pw8Azh/WSCan81SFu6C0+euPTLUKntFwk=,tag:xCsE6Pap/zRfE7pQqHzR+A==,type:str]
    clusterResourceWhitelist:
        - group: ENC[AES256_GCM,data:KQ==,iv:lYe9Gc6vWvvRvxIfLEvVx8IL3XJa1MTL8d+9eWuK1yM=,tag:G/GZnWG12Iwtu0Z+lc646A==,type:str]
          kind: ENC[AES256_GCM,data:Hw==,iv:v7G0+G/O8t1h7IQuuUnX2GKmdKVkHKfg65lXntTAvFM=,tag:72Zuy/mCFltMVpLRh3khpQ==,type:str]
sops:
    age:
        - recipient: age17nqlfm7qj72hgjfs82vqwcfatqymqngpwvp7v999crs2t5a6tu5sd0vcp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVGJWczZoOG5JUHJRSkJx
            QjFCTnFOVlRDV05zWkl5alNsa0Y2MlNkVjFJCjZBYTZ3SUJOcGJuTXpOajFHcndQ
            Nlczb3l3WXhVSXZjZkwvQ2RtNXQwMWMKLS0tIG9NMEI4NWk1dW1ERFcxVlNXV0ZT
            RkgrYTZzeW1EdVU0RlZEbnlJOGNLTUEK8kLpkMvzhfnkHkk3n4zkp0WKrOYogr8f
            9MCSAQ0GBcTFkhXBOVOZcT3qxj+2nloNyt+UDmVUiuUCC95unoUSCw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lgmay2ca3aydsltkxjhz2qc6ep4rqdpjneye3lxra0h3a5k37aeqjj2ue4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3a0Q0YUFJaWdkS29ldkx3
            VXloeStWMUtncVVXQlJQSStWTWlyZnVqb1FFCjJMcjhGR2hVQ2oybW1MVEF6SzZ1
            ZEgxeE1tanhBTGQyRkw4MEpZQnhQdlEKLS0tIHFlNll5ZGp6emJkY3ZCK0Z1RDRQ
            SzJOZk5oUEI5SnV6Q0lITTFadHFXN2MKi7YkZYfuKB8q3v/kQzjLLKafOxrdCilo
            ewLR2fd2JZRq/fUg2o2isuIoMbzA26+v5lMpyO971HIVo7jLwEQNtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T17:08:19Z"
    mac: ENC[AES256_GCM,data:O5G3RaGdDoPlyV70OrgOjlY1GLbKsj22UnhU5iaiH9qVTekrNI2ATTWo1T8KCiMtResX0U5sh69OUgcL7tYehflK4gthOeLaH/kkWWrZg8yCzdOL/w/VK908zu2/C8TJ1QQ43bsDPiiOscpTSTKQDA5ndjqyI4rHOMieEbtMLDI=,iv:a5FiyrtTekeh9d7hGDvKj9MBvUef0p3LCBuwJJjsSr0=,tag:fAiiJwtn0pqanzHeh493zg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
