apiVersion: ENC[AES256_GCM,data:aA9kiIVNhG7iyOIERyXiVZk10Yk=,iv:E3AXdU+4u3mua39U8m2Ba9OPtM0BlgMJGLU+MXYb+qo=,tag:55T7wNqrLBKUEPXq4FCJww==,type:str]
kind: ENC[AES256_GCM,data:tl/RSNcyTpVW914=,iv:1f7BEvirxs7sw4ben1LL7sHAdOoxRSzme4NbFXDP3l0=,tag:w9/AWS98KFDaPHEGUOdvyw==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:rXI=,iv:PgZAOxmqw4dG2XU2YgkMfbzpnV3GHWDJOZ802/SeIqM=,tag:6gukU8PzQfPN7zUa0JB5tQ==,type:str]
    name: ENC[AES256_GCM,data:4SZZwL1+159qGHuSlZOk8vhCEj3JKFq2bVmkWAQo7nhOBmDo,iv:Jk1Tgp9aUBFhbgauKO+PoOZKxujmu6Y0ioVJ/y13Wno=,tag:on7uIDI4Gx0pVtylvEzVdQ==,type:str]
    namespace: ENC[AES256_GCM,data:QL7VDm5R,iv:NWBinKqGjlU06xgp3NwIq6T84RjgxTno7u1Pa/8S9Bw=,tag:wksYy1BgyPraa9RrG+1umw==,type:str]
    finalizers:
        - ENC[AES256_GCM,data:nd+ac52tShKsZaSS91PIa1xUZ3rm+NiHUUP1Gu4NAlLDSSeoP/g=,iv:KVGQgnWqk6pDLS1vjj8U6J50C/1Aq6ji/eugd+gyEUQ=,tag:CkepyNmv/5u3n4DEY003Pw==,type:str]
spec:
    project: ENC[AES256_GCM,data:IaOSKe9sDh8VXmksXcQFVzJP1uK0jQ==,iv:4Ta748YYrSIHPjMSzPWgiVBnhSDcBSa2FhI694b6L5A=,tag:cPxjQsOB0/+lGoaaUSGMPg==,type:str]
    source:
        repoURL: ENC[AES256_GCM,data:Ifn/FQI+nH4R9Kc7JIcOMDb3lBpTQ/5OeNcNp+dUro+4vez8,iv:60jjHIDiQQ808BVyXS+Sjs1komAVLUPvuBFC6WT+gLc=,tag:9OUxPSdKVigHFxq//NYdYA==,type:str]
        path: ENC[AES256_GCM,data:k78xqkBZKCcjuRhj0Tm1W/5+4yUNL+8uIBNDZ4XBRWG1F6SmQEfp7r0oOPqSr1yw,iv:8aZk47wjdLdXZIM66uK368D1wzOlw1MubmSqEjZJ18Q=,tag:XffCPUIkNQWVv785GTO0Kw==,type:str]
        targetRevision: ENC[AES256_GCM,data:AhNsMg==,iv:dczI8Rn+u6DEKJX1yTRhkBAhPf0NvzODA6R70pzyHuA=,tag:0OfGbWcQRo8QWA6O/a7K3w==,type:str]
    destination:
        namespace: ENC[AES256_GCM,data:S513ABZS,iv:IY8VuMKJ2e2IEC6icMQnWtjbs3M51L76LcFzEayi2sc=,tag:Op5Bc/ZdAdPpzkjfGUHjJA==,type:str]
        name: ENC[AES256_GCM,data:f1FqZaAEtVZeOA==,iv:AwbdWvcLQqjnopLW7i8asJGHFSkrh0/jtoAds6IX+IQ=,tag:gPlsIWXCwKW7dqcHeIxARg==,type:str]
    syncPolicy:
        automated:
            selfHeal: ENC[AES256_GCM,data:KxW9Lw==,iv:6PuwryvxIZTedRvRKL+CYRwNvk+k1OUWIBzFd4qMrBI=,tag:mOrWhkoMC3t2lzibZuMHHQ==,type:bool]
        syncOptions:
            - ENC[AES256_GCM,data:CcxEW4YSxw8K+yU0kSBcvyupNARrySc=,iv:a0mXkbbHx8PZdMG0P3HF1/6770Jr8xItLhUbyLfCggo=,tag:eJVLrcix4OEyto9gDPCOVg==,type:str]
            - ENC[AES256_GCM,data:PpVYEUqYpUE/n2TfCbYuIz2Y9y/5fbl/Zg==,iv:z2g211S65gHMA/fAIY6c1kqRHuHp3cEk6CqZ5hOLhAQ=,tag:yR4YOWzhyf8j6VKC36LsUw==,type:str]
            - ENC[AES256_GCM,data:BB46wKnPeFF4ZHmDzznTGUh4h6g=,iv:TzqrEaQpi8aAVE0GOFGRqnyn3dGFIFSHjUDqQzf8Eco=,tag:vrLFORcWh717OhCxKovZ5g==,type:str]
sops:
    age:
        - recipient: age17nqlfm7qj72hgjfs82vqwcfatqymqngpwvp7v999crs2t5a6tu5sd0vcp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeWRPR3hrSjdvaWx3OThr
            QWJvTnBqbU1RazFWNUhOSUdpcjBKSWFUeFRNCmpBSm9yTmM5eUs1VUprWm5lUVpU
            RzJiUC94RkJJRDRNdVFnSk1hYWpnYzAKLS0tIDFqQ0kraWpkekVrTzUwK1Q3clJG
            eTJtcjB4aU9mQ2p2S01MSnhRTWdKVVUKgIXAMZsEV/z6AM2UdFhBaZCpNDb3WgGu
            CE/i7gxlEOSUU3zVxLUMoNur1A72gHop/iMu0qGR0pmYi66oPDVNrw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lgmay2ca3aydsltkxjhz2qc6ep4rqdpjneye3lxra0h3a5k37aeqjj2ue4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRTdsSFl2NnRUd2I1OWlm
            dnRPbUNGWlpJd3VvNGtSRFpEQnkweU40RkQ0Ck9qZnJ1a3l2Z3lnUEk5OWxFRWdM
            ekJVMDZSaHFVdGV6NDVqZ2VGSzF6R28KLS0tIE1uSHpJdDNyaHVwa3Z6eS9ML3g1
            WkNtZWxWUVc4U2xGWDVRZzlhZ2dzYUUKCFD5NFrnFO85aVR25RSgamKeVCTu4xEr
            XOLC21WV8y8Xyx3Zkk7IuONNktfRc5OfROiqk67QKN8A8SWViA2Lmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T15:24:53Z"
    mac: ENC[AES256_GCM,data:GPdiV5TQ8vu08+k+CBTJvpAEqnOCaIWV6di4SKdRxjsGA5t4fvY1mSi3reYYgJbkx9+tnCanwHZtP1WUgspHGflEErBshZRQNFsoLasnYZBntgdqK+7FBZVXWs8gXg5fJE6o9b7luY5wg6ShTOhcMyTYo3RJ1N3Mk0JZwDvGYpo=,iv:9bfwzWk6smGLdjcHaJTO4K4m9uX9HzannHOiZIf2brw=,tag:miMBB0X6YuPG/QjtXGnvQg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
