apiVersion: ENC[AES256_GCM,data:l4l5TMFb3HcUthMcp9OPsDFpHkA=,iv:TW7i1aIC5LEsTYLBXCnsSCmP3Q+vXXupVljjRyWtOx8=,tag:OUF5LtPw40+iVpAd7Kuo2g==,type:str]
kind: ENC[AES256_GCM,data:Ib4AUpBWWSEmYLk=,iv:aTcVeujwLixh7X6WJoYchA4AyzxAtot7/41RWNgmxRk=,tag:pR/T0s4ZHt/g3kgLuWt1ow==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:c/s=,iv:clG6r9OSQimfEXatemGeryTARc7OlPnw0dcvB/ga2Zg=,tag:kUYXTV6ccDQoAFR6Hqh+Tw==,type:str]
    name: ENC[AES256_GCM,data:lpTTl0hKKXEwisrUuQciREDDJEZ1mOsU7fH6F8i1LU+rGPvFv63I1dTLtDEPbA==,iv:4ojmdNlQJ8TXsM6hTidDsFduqOdIn4/OEoNknAI2BJI=,tag:SsDakpiLDxZ7OamSEi2Zrw==,type:str]
    namespace: ENC[AES256_GCM,data:8ZWCsdIA,iv:1pnpmUHJhkQQSILK4NPHntDBCTSeawtFkOf5Wo07b6w=,tag:Q6S/iJOyFxBQuecZqL7u7Q==,type:str]
    finalizers:
        - ENC[AES256_GCM,data:dYR3jGSt8B7PpKXmEAmtWg5OhiAEWR+3gp1RgEt6V02AkOSGgEo=,iv:yOcjFRc/O9iTuCeOJDP49sR1PTn+PVcLtZu90js5zOQ=,tag:zDaAUNG99HBOIQLiPXOItg==,type:str]
spec:
    project: ENC[AES256_GCM,data:alVbBqjihZhu2LQwS/XWf52U0swRfDMnSre183Ur5VA=,iv:/jvXuBB2ivZQY/O/kuMMic1OT7/gjOSYVVm3aux5A58=,tag:J9zJVCeACXBzN4G+j7rOpA==,type:str]
    source:
        repoURL: ENC[AES256_GCM,data:3tqEoT7rCatjf7bbf/aZHBvIgE30yDDq59Ub9gryYXiD2ssz,iv:KRjcqY4BY0kcM3wvQcACwHBEw2Z2uwMEEcyTvN+1KwY=,tag:gyFzjk6dDPiykiT+8Ntb0Q==,type:str]
        path: ENC[AES256_GCM,data:y55BrhHZaKUsr75FMGXmIwY5f16EYMKiRg5/JOZWst/q2XaLpnClN2orS8DgSG7Y,iv:XjJC4iw9N7a0//qHKa6Ae7NcV7KpyCXIPPvxOta6n0s=,tag:65Omj2XHyNsMZwzRJbLJMQ==,type:str]
        targetRevision: ENC[AES256_GCM,data:mFm6fA==,iv:CBQAtxUKEVjbfUbzbNfMwRCPXCcnnByxvkB/fwrwXnA=,tag:+8iKIrvfUsLBk9jnnFDqTA==,type:str]
    destination:
        namespace: ENC[AES256_GCM,data:DIsAySJv,iv:Ub4CJuj0n1Aptpqs00dxTMgmTwBY9Dk2RXnAnA1tSgc=,tag:OovVQyRyegXtNvOKV7qPyQ==,type:str]
        name: ENC[AES256_GCM,data:jXuYACKhw40X4w==,iv:PPuJNZpC45it2L7Bq2mWsSq12F9m3EWcu1y9OzWY8AI=,tag:totORZ4AUIQYzbtPWu5Jpg==,type:str]
    syncPolicy:
        automated:
            selfHeal: ENC[AES256_GCM,data:L4Kcmg==,iv:SDDe/PVhwMrjtnePQHSG68V0+nntXK7sQF68c2/UhtY=,tag:AjpCxamOGnfFvHsm8I2RrQ==,type:bool]
        syncOptions:
            - ENC[AES256_GCM,data:YI6KiniBnW+nyosOEu6CF4XgzKVpZis=,iv:1WH98xX4zpHXi34Vor8qcvyzAZsynjwBJGooD+PSdfo=,tag:N8HMnK+IF0DlHc27oJEbJg==,type:str]
            - ENC[AES256_GCM,data:mD6CQPbZid+LRQ8Wbob2afyNoWXMFUHeIg==,iv:p1v8viWOe7cmP3AF7B+4OixI8vE4mnazZlS/Jxz4GP8=,tag:xwTQdIycwbt+sGutTp5Q5Q==,type:str]
            - ENC[AES256_GCM,data:Sr72nLB4Esire6FBlYwoOIC0Vpw=,iv:JYIQ290yUkp8QCRILdXBowajz6anVfrvB/9kLnHSAAQ=,tag:fe16pKAgLmsA+F2C+3u5HQ==,type:str]
sops:
    age:
        - recipient: age17nqlfm7qj72hgjfs82vqwcfatqymqngpwvp7v999crs2t5a6tu5sd0vcp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0U09XVGdrd3hCcXIwY0hY
            OTk4V2k1MlJ4VVRyNHFNcnBobzA2STdSRkZRCnpRZ2lhSVRTeGpjOFpxWEhCeHlH
            STlWVVBrakhxbEc0VU16UWt4M2daQncKLS0tIHJlemlXRGJlYnBOVS9pVm0vVkJt
            N0hySmxTOC8rNzNGbVBzVUtGdUlXQ0EKRHx+AzehveF+JYCLgis7AkNM7mU/kVpN
            Ca8+gaG6mghOf/EjpdzfVEBnY7wLHpHnLhrFlCSLmo7nb2ueTHd5Mw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lgmay2ca3aydsltkxjhz2qc6ep4rqdpjneye3lxra0h3a5k37aeqjj2ue4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVVRldlcrTndFeFBIV2l2
            UTB1c2tDKzJHSVd1SWRTMWtqbmJYMlNaU1UwCmhHdEdaajI0clJPL0JrbHhVdysz
            bmg3RGdydmdQbnlhYVh3QUgzekU5M28KLS0tIFNINUhpRWxVZ0VXYnR3MTRWV2RT
            RmszaW4rVk1iQ3JZcys4RW1Yd2Q4VFEKdyIurfYIL9iIr0wSgx/3ZubCTOijKr8A
            7rktDG/Wl9uyViH38JpSftzRAS6mA/ReB22wgipLS++FlC6P10caXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T17:08:14Z"
    mac: ENC[AES256_GCM,data:9rn6YWn3WpMLiiGEPP0rcue02vdtXCnUvMAoAz1GXmnvQ3gVdKd/Eon13CCtcGYyZnG0nmzMxVpJ2SFcskdxnh351aziVLP2idLs0nwoUAurvktVnTQhtD0cKcKh1aWXBGa1Akw1XEsbvaENbHMsuK3VC43EvADH2fiEBFkdueE=,iv:d81N4YqccLy3Ch07fy+H809VyvBEIA5Io5FN1oS/tWE=,tag:yYV80EALG+9+tYYURT0TdA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
