# Lychee link checker configuration
# Documentation: https://lychee.cli.rs/#/usage/config

# Accept these status codes as valid
accept = [200, 201, 204, 206, 301, 302, 307, 308, 403, 429, 404]

# # Exclude specific URLs or patterns
# exclude = ['.*ssh:.*']
