$ANSIBLE_VAULT;1.1;AES256
66376665323334636363346265653634373435666165343564363662343134666533326137316534
3235363131623863393033323234303334363935336235340a636334616636633639386431613634
34363263356131653638636334383333343335656334316537376163653666663638373230613861
3739666239616633360a383361373164343062336330306135646434626434393862353830393032
30653737636533303031396435356363306538623437653635663836313866373334636437383361
36383761356531346136323766313365623463613537356231366532353537383065653330353337
35353934383334393835336431333137343861396538386363306531303335323632663235396163
32626661343666636536363536353339353037613762636464623961653761663433316538393664
35343536643935316464363136656364376263333630663233356435616461653435343537343232
32383062666531363061616338333735373231306539646438653437386666373561313934306564
38636363356236643236353339316130633730663062376263366564616637373139323330643732
32373262613932623934346635376636626334646431383535393864613835346362636362386265
66633833646336353139326239646532356131633966363262353333303437303437653033386261
39393163613939346366383135623837303535376637373437306261333262646133306661636231
633265343738363938613233376435313463
