pve_tokens:
    - name: ENC[AES256_GCM,data:C+R5k9g5BeA=,iv:vReuDPmXZtIKi0FHt9E1yoBY75w5QaEkqzPKKlds4PU=,tag:foVnT4eHYfHE++k+3rzwfA==,type:str]
      token: ENC[AES256_GCM,data:30EHDsh79i8SW9ms0D6aqeY5mgfQo6hBkh9jqPJMJnyrYtaA,iv:0eda1MHE+TuAud69jOmK0GRBQstQJlCkQhEkZF9hcm4=,tag:uhPqqmU3T7457CZtdP9nEw==,type:str]
    - name: ENC[AES256_GCM,data:w8wXcoldesaMyDv1rw==,iv:Y0ogYw9HuHSrhP5JlT+E2J3nZHyklNv0UYTfihlznD0=,tag:pDbOkjzJSfh0D8hGljO2UA==,type:str]
      token: ENC[AES256_GCM,data:O+IPpXf2PPdTOIGQIlZQqz+drL1E1oajzsU2ZmZ87ZZyUYZq,iv:KkAsjjmHB21PypK6LSLOtQAvMf5i9Iw7x7nED8y0Ehk=,tag:Wd0r+s5YjC6KT07Wikvc0Q==,type:str]
sops:
    age:
        - recipient: age17nqlfm7qj72hgjfs82vqwcfatqymqngpwvp7v999crs2t5a6tu5sd0vcp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQ3I0d0FJVk1NdXNCUGxa
            OXF5OEtiZko4Lzh5TXNBK1o3NC84N1pJcFdRCkhqZndkVlNXakJkL1ZidDVTTXZU
            YXYzUFNucGIvb1JLY0dqcTVYSm8yRWsKLS0tIEtHWnM4a08vcXQyR1JlRERJWTZM
            aEw4YnJCU2k0UzlZQlVneEtsNWlORTgK84IN4RtwPYI/4D9a+BOElylF0DStR+kK
            Dvsq3onWhj5i6HwUXsmMROo6p6W+iOo6euMli6vNVxG3ofzU1oUhrg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lgmay2ca3aydsltkxjhz2qc6ep4rqdpjneye3lxra0h3a5k37aeqjj2ue4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRS0JmWnNRWU9MenB4RHBs
            V095aEF5MXhjZDV2TUdRVkRTV3ZXdGlvbHgwCnlCQm1ybFRXcmVsTUQwVUNjbWxF
            eUVQTHhZNUl0Wkk2cjhibDlpM09NT0kKLS0tIFZqazYyT2FSUkRIOCtBaHc1aEJx
            eCtvSEJaUXc5V0J6aG1PSkxRQTB6Z1EKCLhuJUR7ZxkwrfD+3xQFfWFK+wuS6api
            cn/lHtvMuzSBVrApx37FOUuxSScnrePo63jWTb5mBQ2k3WqljScc4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T16:51:19Z"
    mac: ENC[AES256_GCM,data:omnqU7Ofp3wSsVV/VZNqieLL+S8e3SEnMnC0qpXoxIWD6Coj8Lh72dLPp7a9Na/abt2Rd91Qhsh9O+P11B461ciC4qNPkqUApStz14qwHaRNpWcBx/Z6mn8HYpqCkc07XxgNVDbyGWdi/XSS7Mq+QXyiDWsIPlflXIM5SvFRnfE=,iv:xLesvYaszk2hAcbbAa2p+ZinzjLTlS7f9VrMvjubzRQ=,tag:KutpRp9CUzU7QoRWMVg1tQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
