pve_tokens:
    - name: ENC[AES256_GCM,data:ovJkkxR4gCg=,iv:BszlfyiOhdGV0QTLRo76D0FkiTUdSbGUBnk3FnkcFvQ=,tag:sTIoSDaOpcvhyysjeAyHpg==,type:str]
      token: ENC[AES256_GCM,data:a47p78thxo02UQYHFYmH3kfkx2r5qqM5xTMNxGI9exDnRq5U,iv:wvvsRREi95oWGoGdJeIIPNsSdf1no+774jz6M8lPmYE=,tag:f3QoPan6BFOGmZc3CbS6Ew==,type:str]
    - name: ENC[AES256_GCM,data:KpIga12fzZ57qNNgdw==,iv:RMoq8vGmHuIvdBKx+yhe8ZSGI+4LQhebpRmMHqyeXuo=,tag:g+WREgzsxmJ4Fz0Y9Djemw==,type:str]
      token: ENC[AES256_GCM,data:SnL5E4+o59T7E0e9Fu3nRmVGYRVd39KtWCcRZXKLToazlgOh,iv:wg/YtH0MwT5dBvhBGqcsjafjEcFGh0Y6XjP+HzJcYEI=,tag:GE3s93Mm+V8XYewwb9oXew==,type:str]
    - name: ENC[AES256_GCM,data:ExKdCDJ8EVgI9L4VobA+,iv:AQ47Vl/PfE1qAQOs9ss1BK7ISmwgppa+mm51npRvrpo=,tag:y4lleVPF6hqHgYO2JEoskA==,type:str]
      token: ENC[AES256_GCM,data:iJokHRA7jFqRKAUqaFcw9NV3Jpn829wS5O/q5V/apCF4Q2/T,iv:Jv8hdFeLZWAuOuIrarWLj2uwaBGzF4oB/HJxRX30pE4=,tag:eb7AqXvBZzWlf0Zch4dAGg==,type:str]
    - name: ENC[AES256_GCM,data:018uJp0hs6zrNznl2Hhr,iv:rn+TlPJHXHzDx4/WXXPjgjBrwc9LG6TNLPWht85ej+I=,tag:A071mO36Wd9JyVeigCrhhQ==,type:str]
      token: ENC[AES256_GCM,data:4LWUW8cgn7D2kFZLKEvuKnkLQOx16GdW0DKRX7FffrLg3yqd,iv:JVqfMSW/j5E+vP4BPJ55Ws8BbR6g+RuPMKnyRm7UPU0=,tag:eMnLYi0Ds6gpWE8HnnXKyg==,type:str]
sops:
    age:
        - recipient: age17nqlfm7qj72hgjfs82vqwcfatqymqngpwvp7v999crs2t5a6tu5sd0vcp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArN0Z6dnRoM1ZiaXNad1lq
            OEE0MXJWUXVXVExSZGl1RTRwRm9nckcwR3pnCmd0ZmRORVowQzBPYUVaZlZJVitU
            Qjd5THVKZzF5NGRwaUdXNmluY1pGSmMKLS0tIFpWcFluRlBFaGpNV3JCUG9MOHJo
            K2RpTlpROFVnNVRUbzlpZ1JVS0dyY2cKwnPHbwE62L0YPPD+2txyPwvfPmBZvjz0
            vWP9BoSHjFOquYTvvtfMSHQVJeLRlCLqTHt8PikKyzhzT8BK1zqg3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lgmay2ca3aydsltkxjhz2qc6ep4rqdpjneye3lxra0h3a5k37aeqjj2ue4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TmFiMWJsS3AzTmdFcFZr
            dTBxS2VlVXlGRkdkT3YvanR4TlRKd3U5Qml3ClRMZTNvMXpzaU9zdXQ0SllURGVk
            QzVVMFRjOTl5Zk9MWkZLdFJqZ1pWTUEKLS0tIFBZT29EYURzcEx6RVN0UnJpN1Yz
            N1Zib1VwUUZFV3QvRXZqOExhZmFycTgKkklkG39oSHIL0xF5DX1NURBtGlHFm3w8
            Pgq4ne8TeKDzrLp/phIu1d4u++R7o/y+Jfm/9nekS04HyQvXzHPClA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T15:57:13Z"
    mac: ENC[AES256_GCM,data:geznjCU/cYIMyzYM6EXS8IWZ7TpOs5DvCYLVcsSwFOH1UGC1/u5m+gqFjcdmbNbcwbiWVGPNzQvm2be5uGriKcuwDh99e454nMGo/KOmzBfj0C5Z1+YgzoJCPWz8lsNYzB8IrKRbm99LtH00Y4wPSJQ2fbDKtmA4z95zlwM6Q0Q=,iv:nlhSwAxfRqbzm6BuEBvIyH5b7fEsgx0BKbtWKv1omHQ=,tag:hQN3mMkEyxZqR++RzPL1fw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
