iac_user: "iac-prov@pve"
iac_role: "IaCProv"
iac_token_name: "iactoken"
iac_pve_privileges: >-
  Datastore.Allocate
  Datastore.AllocateSpace
  Datastore.AllocateTemplate
  Datastore.Audit
  Group.Allocate
  Mapping.Audit
  Mapping.Modify
  Mapping.Use
  Permissions.Modify
  Pool.Allocate
  Pool.Audit
  Realm.Allocate
  Realm.AllocateUser
  SDN.Allocate
  SDN.Audit
  SDN.Use
  Sys.Audit
  Sys.Console
  Sys.Modify
  User.Modify
  VM.Allocate
  VM.Audit
  VM.Backup
  VM.Clone
  VM.Console
  VM.Config.CDROM
  VM.Config.Cloudinit
  VM.Config.CPU
  VM.Config.Disk
  VM.Config.HWType
  VM.Config.Memory
  VM.Config.Network
  VM.Config.Options
  VM.GuestAgent.Audit
  VM.GuestAgent.FileRead
  VM.GuestAgent.FileSystemMgmt
  VM.GuestAgent.FileWrite
  VM.GuestAgent.Unrestricted
  VM.Migrate
  VM.PowerMgmt
  VM.Replicate
  VM.Snapshot
  VM.Snapshot.Rollback

pve_users:
  - username: "iac-prov@pve"
    role: "IaCProv"
    password: "{{ iac_user_password }}"
    token_name: "iactoken"
    pve_privileges: >-
      Datastore.Allocate
      Datastore.AllocateSpace
      Datastore.AllocateTemplate
      Datastore.Audit
      Group.Allocate
      Mapping.Audit
      Mapping.Modify
      Mapping.Use
      Permissions.Modify
      Pool.Allocate
      Pool.Audit
      Realm.Allocate
      Realm.AllocateUser
      SDN.Allocate
      SDN.Audit
      SDN.Use
      Sys.Audit
      Sys.Console
      Sys.Modify
      User.Modify
      VM.Allocate
      VM.Audit
      VM.Backup
      VM.Clone
      VM.Console
      VM.Config.CDROM
      VM.Config.Cloudinit
      VM.Config.CPU
      VM.Config.Disk
      VM.Config.HWType
      VM.Config.Memory
      VM.Config.Network
      VM.Config.Options
      VM.GuestAgent.Audit
      VM.GuestAgent.FileRead
      VM.GuestAgent.FileSystemMgmt
      VM.GuestAgent.FileWrite
      VM.GuestAgent.Unrestricted
      VM.Migrate
      VM.PowerMgmt
      VM.Replicate
      VM.Snapshot
      VM.Snapshot.Rollback

  - username: "opnsense@pve"
    role: "OPNSenseAutomation"
    password: "{{ opnsense_user_password }}"
    token_name: "opnsensetoken"
    pve_privileges: >-
      Sys.Modify

cloud_images:
  - name: debian-13-genericcloud-amd64.qcow2
    url: https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2
    vm_id: 9000
    vm_name: debian13-cloudinit
    download_storage: ssd
    download_path: /mnt/pve/ssd/template/iso
    vm_import_storage: local-lvm
    redownload: false
    recreate: false
  - name: noble-server-cloudimg-amd64.img
    url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
    vm_id: 9001
    vm_name: ubuntu24-cloudinit
    download_storage: ssd
    download_path: /mnt/pve/ssd/template/iso
    vm_import_storage: local-lvm
    redownload: false
    recreate: false

resources_pools:
  - name: "gateway-pool"
    comment: "Gateway Pool (Network, Firewall, VPN, LoadBalancer, etc)"
    pool_state: "present"
  - name: "virtualmachines-pool"
    comment: "Virtual Machines Pool (App Servers, Web Servers, etc)"
    pool_state: "present"
  - name: "k8s-master-pool"
    comment: "Kubernetes Master Node Pool"
    pool_state: "present"
  - name: "k8s-worker-pool"
    comment: "Kubernetes Worker Node Pool"
    pool_state: "present"
  - name: "datastore-pool"
    comment: "Datastore Pool (Storage, Database, Backup, etc)"
    pool_state: "present"
