$ANSIBLE_VAULT;1.1;AES256
39363731663966373362363561343437386130646538656332363961626532363934333830393833
3330656432346230613536643030336635396663356238350a353333633730343231356266323931
30666430363532333436336437333533653865396566613439626439376530373864623636303537
3631656534656465390a383866386565303665376632666131383536343431343032303230633637
34633837306431323130336666623233376634313939636637343036643339316661306232303634
37313633336636626332323364323061393333376432656130383239393139656631393866396261
38383661376338623962656164633765656332656138666236663064333365333465626335626438
39303863396231323733336165343865333761643436353235373263633730386263656461383038
38383137613332396664343162306535653234383031353933353266623964663063
