$ANSIBLE_VAULT;1.1;AES256
38333232613835393338393139383933376661356135306339626338386333646561346339653464
3939646336653638623363336333383031343833323537310a653136643565663531346163633934
34623732303431303063643664356530376431343465613166613130646562353439323935613639
3934303835316465650a386131323434346335393862343863653236363335643933396238356639
36653334623837333061646130623031303632323835346663343161326362316437623732366138
63663966663033333737306331613538396237653965653965666338363635663130326562396336
64333332373735343332303032633262626539353066393466396538306139383864663366653963
66353036313161346464333636666436323833636431643561643230616664366533323732623465
34383931626130383330643031303837646134393332343563333938323064633930356130376466
66323737363563393134343938613932393333353263306631326139326533333264303861663334
65326639396334633931633832383035613938643961316536393764373537383163316439393464
38306539653034613165326532373435333837633965306633653134366636663832636337656130
38636533346534633164323661636539343437613237306466353865316239333837613162346533
38613439363431613364643939633133396462346531343936363262396135646536323563366565
65663837303736333536366561646562613135373065613534663938633136663632303763313866
38303234366235626465663635616636613663616531323664393632333866646239343832623638
61353465353264316663636632363766616262616161313032323362323633643563633334306335
34303531323264366435653733613235356138396638643763663634643062333337313261353136
30313265386335303534613039643163333537666434396438623730646266633831353139663766
63333737353438326338666461383266343733346262653039343733353436343638303133633334
37336637333462353438393333353362336530346532383062343663353564366561653038633938
34643938626465303230386365326133623530313236356635333663363665363463383265666166
66343039666638316430383263333134343239363330353866303663333465306163303864353339
37396538336161623635376230636135323464353939336263336336633939326233343464396562
63663430626633613033623036343933343265303038613436613663636534613964623835336632
36653938656538356261623832376434643434363634373133323366306237393264376632376339
30613064346662633835383139383738353665643538336434623233623138333434383239663730
38646563666530386163396636333263663531393364353665303736323962363239353964333864
64323833666532633831306239653931303830363331663138623739656366396664
