apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "./cluster-autoscaler.yaml"
  - "./kubernetes-replicator.yaml"
  - "./reloader.yaml"
  - "./cloudflare-tunnel-ingress-controller"
  - "./external-secrets"
