apiVersion: ENC[AES256_GCM,data:d4Q=,iv:qATWAwvnUv+y42Bz2+81Bx3w59ZYxQBziBNyJEgLC04=,tag:d2WvYQczV9zfEcF9S72+Yg==,type:str]
kind: ENC[AES256_GCM,data:+apoIbRi,iv:140h5YPr+9xnSBMYW/ixibUxfH3IGoWMlU/YJx0DFNI=,tag:X/JuDbXGYv91t5AuF5pWqg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Xo2Dp61YAa37MKlUAJXWhAhTot2KJ4zp6ZpCczNPEqs=,iv:pwQbojVYFjZ2xHDGBKr1/ntst1VnbsjAoAHqJrPlUiU=,tag:BLSwqd6mlWF0b14h/OkgHQ==,type:str]
    namespace: ENC[AES256_GCM,data:YGmxLFH/zK7LlLU=,iv:RVnJlCQh9UmEgWW4DV7ez96A/TNe00/1an8Dpufjjnc=,tag:J/MBf1pjgTCd2X68iXzpIg==,type:str]
type: ENC[AES256_GCM,data:QMaZic3/,iv:9oB3QRGDf0YqIQbBeXHiBGVJczqurX0U812mgz/b8rQ=,tag:zuC2GUX2Di9+ZrKW4d+fDA==,type:str]
stringData:
    config.yaml: ENC[AES256_GCM,data:DjbVlYlQcBQGDvZOePVC2OiLUGO+AKeA8t6mYqgvg8wZQBgGfOYW1fMC3jU3CN3xG4lM/2Bi1w4VZm3nSVtlViSOV4hurHgUrB1CyCYT29n1oXuqQm+9AppWHtiucWyGhY6seJxOhvvRYFynqCRIzlhLwBx+Msz4MkI/Kc+DxIfnSz5fGw5/UDkaK1sDWy5MQ1UqRgUoUI25ymfPq4YXjjLFjTtZtiN/59XPDIQkD55LkBc3XyWw3jdQ/SWakHvrF+Voeu+J9ZE=,iv:GnMeDdDyKCAlv1LyY45qtvoyp+7yhMsMySbQov544JY=,tag:Jt9+AmrOszhhI1F7J2TKrg==,type:str]
sops:
    age:
        - recipient: age17nqlfm7qj72hgjfs82vqwcfatqymqngpwvp7v999crs2t5a6tu5sd0vcp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRFNzSksyUjNpS3lmNmdI
            TXNXSTRGZFdWL2VHYTZPU2tQanBndzhSRG5nCmxKbXZwajJyTS9naU1NSng5WGZD
            czZ6MFhoTHJmditjZmxhbzg0SmxOcmsKLS0tIGVzZnVybDdMY052dHVSTWpjVlg3
            OFY3R0dZSkY2elVqWVNvSFR1TXZGQzAKjbJnBLaZ/4eyypSX3lCGwIi7tMq2pcbO
            SWqaf8oUVs0P6RJti+NniLGHNZWmc0RIqzuPPIvSk4t8CneiTm0Ibg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lgmay2ca3aydsltkxjhz2qc6ep4rqdpjneye3lxra0h3a5k37aeqjj2ue4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeVI1bCtITUFyaTJKZDh4
            TDdhVWhCb3pXMzBUd1UrM3pNcHY4UVBZekRzCmFqaHNhTFoyb2VqbmtjaTcxQjc2
            U0lLNGg4SjI1WTRzMXNRd1RGL0F5NDQKLS0tIDl0TnVtOXh3NjlZcmdDclJPWVps
            Umd2YU02VzVGdndDNTZzdzMwYWxVMU0K9or5zQVODt3jEXyTBphC6zjeVFrlWwEh
            rT6bhQbWQwoQlMpDh9irOKJRL0kK34pUpJPdbAWPrXOwIinVYEMTXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T15:47:14Z"
    mac: ENC[AES256_GCM,data:X/nMSRmkl+jWkO2vZfpftba0dYhFGNrlIM6aFHtIgNCE0hh5RK7mF9rfohDVGLp7DYyV1eUWP88tk2pkSbklZmruekYRhh+sLYViYxdZOMwvO9PsX/UhK/oeB31rNp8+VytfQmZly8YJJdxF1eY95vrxbkppYW4s/fx1/lo//G8=,iv:+UWVQEWh03Kw7CfBtPhba0ydJL1eTF9D4dv/qBK5FcQ=,tag:IcC+Dr6z0b/gqstMKM/Zdw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
