apiVersion: ENC[AES256_GCM,data:wIw=,iv:+NvsflJgVwxZLXhtVerjLDHzp5Nxd6nMYXdp9Y7VA9I=,tag:Ziz0zfvQOv3heVwt1xUANA==,type:str]
kind: ENC[AES256_GCM,data:u6F6bVgD,iv:pn1cihh64gEkLRqFvw2xbEHFFH0vWgb8tWrFfHYkViw=,tag:onpMuLEPUw1M0Tl6F/J7Ug==,type:str]
metadata:
    name: ENC[AES256_GCM,data:B39GpI8SgxZu/r9EwEsbbGGk,iv:AAT+vmaCMOCdH9v3gRUwAUrwhTXtT0qLaUznBcPmUrU=,tag:v+NMhFwdumDsV+jTQz5ZVg==,type:str]
    namespace: ENC[AES256_GCM,data:wNyOYNFMzA3XqDA=,iv:/hpmv30VL2ktTw6sPOdU4aHtJWQj6mzPfL5NoQFsL2U=,tag:pQwzZzhNpl6l9CaBDegEKQ==,type:str]
type: ENC[AES256_GCM,data:HSH01G46,iv:lA7th8BcVvGX1lxdGHL4GC98VFnhiH29WlPu7PE+aFc=,tag:sZTAt61VwxNUGMI18vMotw==,type:str]
stringData:
    config.yaml: ENC[AES256_GCM,data:+Bc5fa7KtkuFMqZeKW//qIoEOfvBXmg+LUHYWnrIlIpM1eGhzM2hdhCFHqXldOMAVkw2UvwNLw9560Ahx1AqePTwgA8/d0bVCFdy4riZ88f4UfqsT7i+7lHLq5dHIgYU8/qwaYU0vRQWdEAXMN9C77R01PI4moazex04WUsbC/dGw8Y3dskHE328Mr9HPwzExsbzgVgpgeq/Lx/C0jZNic74zEf/PPDf5d1bhjZnzB1GuPwkMdCJdL9HJ5NGoc8RHnwznjXKNCS8ZJtZpIDzW3J2k38z,iv:lEIRAdxT4k6OBdmLNTtKF3HUvfiBCitdvN5yuEltmoU=,tag:+88o/Avv0692MBGl0i6mHA==,type:str]
sops:
    age:
        - recipient: age17nqlfm7qj72hgjfs82vqwcfatqymqngpwvp7v999crs2t5a6tu5sd0vcp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrenBtd0p6T2drdzVpT0JF
            ZFQ3eE9xWHoxbkp1b1RzY2JyUlhHL3BoQ2cwCjJUR1hoSVdhU2FIVjdvbzRseEVk
            ZlZIR2RsazF1K2xDK0lTdThjMnlsQ3MKLS0tIFAvUWRUZjZKK2pFS1BsajA0Und0
            Yk9tdjhoRkZDNHc1b0FUSnFqMzlVMmcKGfpADeCDl2ppiepyq8ABrfl1v8DJ69bl
            iXKv5D6vhTROdopQ4uZ03IpN/duMAyrlH1dkNej0KT422UeeD2JB4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lgmay2ca3aydsltkxjhz2qc6ep4rqdpjneye3lxra0h3a5k37aeqjj2ue4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVGlsU3FhL0xRektGbURa
            TG1TM0VEL3ZPUTNjemRjU08zZExpNnVabENRCkhObndIOGRQRVNWM2pWMnZQWFlP
            VjR6eGk4ZnMzbTA0d2haaUptUzYzYlEKLS0tIEFiMUZoOE0vTXBZNE9RelUvcEZ2
            MEY5b0lJR01OS0M4VFlWYWxiTVRYMUEKrIpFlf87HZsiqI/MUnpAEN1HIrlU3exA
            wpPZHN2086QNDCv/tcSGwPggrXLB1cjUofflIpM05BzenpkQgyaGig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T14:58:46Z"
    mac: ENC[AES256_GCM,data:ikrAGdGLLq/qsCvoVQg0mPwbMLVGE3zYJoE4LTYLIZeC9iNkqm4ATnSybdFJ8TjJ0thNHBmbQFaDHCy3ZyMRd8tCJhpcyp9qG4tTgbTbYk1KI+joGw9i75MOzUztm1eDJ1tm0i6V81LPmtLIC6ne9rTxei7nMvNCBy+LOGH2lQo=,iv:eiTELHgMRl0SYmRH2fJS27Ovl2J2bU7t6jjBzbS+U0Q=,tag:X+G98vNIpLteYbp8A41S4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
