apiVersion: ENC[AES256_GCM,data:+3E=,iv:5xbbN/7xTEoK+UOJ+haKvKFj4IYCp5QuPtyIaJeTNSE=,tag:F0K6ld8u2LMaj0z3+MXPtg==,type:str]
kind: ENC[AES256_GCM,data:c5wXqpv9,iv:5x/MTKlgpO6c9ziZUSGnzxFkAj07m9FL9MJL7vjhI7Q=,tag:MO/xcj/lkVNx5iNeQAxQsA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0V7cAz9m91QAJyqnc2GQpAbW,iv:Zw1o+1LR81qty6VQXP2sCEmwhA37OolQgghEWsj4Y8g=,tag:LKhHROugeMww5uyftpt0cg==,type:str]
    namespace: ENC[AES256_GCM,data:y31RYdaU9nTfU7I=,iv:69JCQ9KWJuxKCk5lmr1CKZwh1RhIGKgF+745bBNOT28=,tag:TZ8wqyBgLu1sxcWRFz6VWQ==,type:str]
type: ENC[AES256_GCM,data:iSh8+Fmg,iv:hjZTp7ODfhtulmK1JMUYoORqlaCRjJmxt0TH8+hMIFs=,tag:9ZjqLYoAt08ucnRfSNyqKQ==,type:str]
stringData:
    config.yaml: ENC[AES256_GCM,data:Gy3sF7M1jtpLa6K2/p2FWa/FtOVen4tUXprwjS/ONgWpa+30SIwCSIiwJ4cX7F3Y6VijG4NPUJ3FeX/ZeryIjE7yKsyyBtZmsy58a0OQgdERFHMWi2QkSJpJaCdaBRrJrogIADfxP6h+vX3x3k7GPj7LOoH36wZ4FCDZSRlAmyK+K+kFNwNCejaSSiVaMp+ZJhHO7l3zXjMRxNpvXONdfWAmGJ8T70WmuoDOVpKNu81THbR67t5h042IpdLCUuloPvCFgBcMcKhCX+eA,iv:1GbhEkPH2dW/CmL+5jK2EKXI0LMVXsTTIRzzNqtfaM8=,tag:1e3tDYlsUunj9T/8gn93yA==,type:str]
sops:
    age:
        - recipient: age17nqlfm7qj72hgjfs82vqwcfatqymqngpwvp7v999crs2t5a6tu5sd0vcp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZXBOeFRsc0pYUnI4amVy
            NWk1a0p4OUUrMEpINXA3dXd3SG4rTEk1SXlJCmZtWmg5SklPb3ZGRElQSU5HajdS
            VDBoUFg5QktUVnZmbFpRb3ZJTGFYencKLS0tIDJpUFpyRmM4K2IveUE4emFTY0FW
            WC82QmRXYVF2R0tWQncwUWlxVTBuZGsKFeizw8i+4ZzzMrmOXxBd5iEMgxmOQNsx
            hUs/aqI2KWRqyXnQBcRHJqi8U2cnyJOyHhyQgeo+lZU2m/uoeAKfuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lgmay2ca3aydsltkxjhz2qc6ep4rqdpjneye3lxra0h3a5k37aeqjj2ue4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZDN0Nzc2ZWlHUVluTXpG
            N3ppVTU4T3V1aUk0YzB1b3lkSEJGVEJTcTJrCis0K3lhTEpPTElERzFCbkFvVW5V
            N0Fia2NaYm90eDU5V0xxeWk2dmk4V1kKLS0tIEVkc1RMSlAvUmJ5Y1hvbTlKa2lX
            TkFCbzBJNWZBRWdhUGIvRzNWdzQ1ajgK0vtKADwtwx+ciY43C5641+Pjs8c3/PKQ
            FWnqkoF0Vh2XY/57aOQuMVddLgbgnMVYfw5H1GsKahqHdNf6y9v1bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T16:06:29Z"
    mac: ENC[AES256_GCM,data:PTh52fCXxFrx8My2gPBP4bZMwJV7MVTNxTZr+WPmHtbFgz5cg5rRAcjefOQWTrSs52GjVd8+OXEdSZoX0nQcBNtxICMrM2GOWd5kA5sLWATaIj+RGkoDInj7N7/QoC4T0bJiqQICZQTnmpfRCm4NBdtqJsTZ4RgfGCMViQ9DJaE=,iv:Bi9p7CoCUXM7JeSFe5A8/wOYvdrcHE2Y74M4umP3JJ4=,tag:UCMw2bsQaaeTx7xIDf258g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
