apiVersion: ENC[AES256_GCM,data:2Pk=,iv:LJTKwLUQ0F849QcSueo4/iu47BmRHC/Clb3+SuqHL8o=,tag:53y9XDqQN0x2HgCUBpxFBw==,type:str]
kind: ENC[AES256_GCM,data:cGqKGPtG,iv:3VN9rlPORFwedhxCP8+fAa/xbj1x8xWFPrNBh3O704E=,tag:ogmlbzoSJ59AJWyLWlBGNg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cKdl57riv20/cZohEu1uC/vWfHiQ/3yzxOnm/2Y1Hb4=,iv:76biZ6L8ohEcirHMwJ0adn0XAgF0+EYbXnJY7872vi0=,tag:ETN2MrCWkyRpsybq1B51qg==,type:str]
    namespace: ENC[AES256_GCM,data:mCPZQ/tc4f0wPDw=,iv:VUwkKwvQGvvZGPbotraJ40+EnRsOj120JLzVd1iUJ1E=,tag:UmIAB4OvPjrcY27xhIS/og==,type:str]
type: ENC[AES256_GCM,data:B2iq+c3W,iv:+N8l1WkMaMYGwLbjcCGIFPb+Z8tXDcOF1Q38/qmYGpE=,tag:refjS4nQFsK05KTYmg7SJQ==,type:str]
stringData:
    config.yaml: ENC[AES256_GCM,data:nT6gvcF2/N0PgW/yh29n6z6ms2ps4ckeaVBcJArUdrbSWIwvEi3J20acQZO03XwqkTdoQOA0maschqdcqm2zIehTDOaRbAGT23a9tYv9FCsDm+79D1wW/oishPh3iyZ2r0H4Op4C0RBUuWh4xUjv4+Zz7FJBCPiwzqn8+PEdzW02JaS5jpILkMGK5wyhkMoUoBKmwkQcYsVgfE9nZ3cOtr2lZopBgfXeABTtmGmBCfP4GViGD1HJUA9tHm7xV9ioZdlgFNx291+a+gVCsqdVeAs=,iv:YjVLF44zJDRFv9+rh+aZb8rgXtUanUuXlftStXiC9Iw=,tag:QlNOL8VteeT2baCNglWQsQ==,type:str]
sops:
    age:
        - recipient: age17nqlfm7qj72hgjfs82vqwcfatqymqngpwvp7v999crs2t5a6tu5sd0vcp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBON1h6OXpvOU5YdlJ0Rm9O
            eDJoS2NZNU9oK2c2SVFONW40bldnejFhY21nCkhET3JETlZtdC9ESnV5cEk4eXNR
            Rmh4djR2bUxqTEhMS3VOcHRJVFNSTTgKLS0tIFdOYW1GOWFBR0t2T2pDbjlkTUxz
            dXMxOEFxN042aFhwWTZjU3RjZ1VoUmcK0bijNIVyxGYX3XD5ukaYh+BnoD32n2Xc
            dk5bDB6NBb3t98F3+NNEYkOtuLslno0KLEePyD9M4CdGM9u/clxiWQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lgmay2ca3aydsltkxjhz2qc6ep4rqdpjneye3lxra0h3a5k37aeqjj2ue4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNGFCTmVCTjJzSTRZdnNa
            NGxCdlBOdTZNVzJXSUUwRjE3SElka1Y0ZUM0CnlmLzNFRDQwSnpHRE5sdHAyMEpF
            dWdjNy90TUM0RFZBMzVFNitXdVlVTzQKLS0tIGtrVklIWlhxTWdXbStrZE5CQnVE
            TW05SDdockN4OXRPemJPNm1KV21OUEUKYD3GoKlMbuD6agc5o8c+nzD+TuJxyo9q
            35kqIOKCkeJV8HXk7LLsaoo/UmMGhrgFq7SyVmuoOvX8ZoL6aMxCYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T14:58:36Z"
    mac: ENC[AES256_GCM,data:4rUeUosP7KTJgHTDSaE18e+LNvMPJko9NjWViI5Xb/ZeUr7U1LpNyzfo+JR3yan5khzQldH+TWEYeU3zHC6Zm04C4q1XBY+oYCt9Matjw+3wLcYghtYDgp/W0zT9/WSYHerU2UNRZM7F7PwT5imj9hP+rRXeppVk2gmZGeJtNJk=,iv:GUx5wrI4rDzQdj9D/qmDQWiNghR/NYRitbWpBdm7rHk=,tag:fKaMySzeFxC9XaZolkfnQQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
