$ANSIBLE_VAULT;1.1;AES256
65643536386462326637643835653430313536643330623464313234313037356266616330326338
3564326161616230323462653065303235353031326464330a323337383866643035376339643739
38653030396234316432373839653561326566333161366663383931343764363832373332353833
3433333833346530340a613164623835356563626365306539633730386665373764633535626435
34363438326431663231646166326432623232313064363065633635333562343039336539626631
63393633316231643535323537333564653364393166353530623939613761383333366238323835
64633237623635323639303763313731313830313238326262613034396430393763616538626661
30376363333034363764386338356237356139663930343733306366613064363263313034333837
64313566613362353032366561626130393031383133613962356430393536353733373639613037
62363162333531353538613464313436363839356533383035333266376461646438613263626435
65366138353864386634356431303166343562356366383665633239643734663364363536663631
36383965666564336562303336616166373966353635316163323732363865313965333839666361
35323061646432363838353830396532323362303830663134623963303766353365
