$ANSIBLE_VAULT;1.1;AES256
65613461363838663865373430626137303435366636313466636162343531633435393164306238
3164346438613632623131343436626535626439306538340a396461376535666138373233646238
64303061643732646435343566313462396133616531626638303961313839646233383562626239
3334653366613161380a306331646561643837393935323338623163613130666532316431623235
39623834336231343231363364323963376337623064396332323336303730663734363162393863
34663638303438326365393261626366653235323839643638343435363566393636303031343830
31353438373634653961393162316431343463616138653137343565613136646363316137396537
66393665363135303539613538346461373336306231323736373664393939663737323830323264
39656632383731303730383066346230646465666165306562633334633565633336363434666335
37613463636666373530643639383366336264353132633436663138363538623961326562313030
61346334363066613334303463303835663630326565623737306663326237333962326132386663
66613135356466333635
